import React, { Component } from "react";

const PhoneContext = React.createContext();

export class PhoneProvider extends Component {
  state = {
    samsungs: [
      {
        id: "galaxyA9",
        name: "Samsung Galaxy A9",
        technology: "GSM / HSPA / LTE",
        weight: "183 g (6.46 oz)",
        displaySize: "6.3 inches",
        displayType: "Super AMOLED, 16M colors",
        displayResolution: "1080 x 2220 pixels",
        internalMemory: "128 GB, 6/8 GB RAM",
        mainCamera:
          "Quad Camera: 24 MP f/1.7, 8 MP f/2.4, 10 MP f/2.4 and 5 MP, f/2.2",
        selfieCamera: "24 MP, f/2.0",
        sound: "Single Speaker",
        OS: "Android 8.0 (Oreo)",
        battery: "Non-removable Li-ion 3800 mAh battery",
        imgSource: require("../phone-images/galaxyA9.png")
      },
      {
        id: "galaxyNote9",
        name: "Samsung Galaxy Note 9",
        technology: "GSM / CDMA / HSPA / EVDO / LTE",
        weight: "201g (7.09 oz)",
        displaySize: "6.4 inches",
        displayType: "Super AMOLED, 16M colors",
        displayResolution: "1440 x 2960 pixels",
        internalMemory: "512 GB, 8GB RAM or 128GB, 6GB RAM",
        mainCamera: "Dual 12 MP, f/1.5-2.4",
        selfieCamera: "8 MP, f/1.7",
        sound: "Stereo speakers",
        OS: "Android 8.1 (Oreo)",
        battery: "Non-removable Li-ion 4000 mAh battery",
        imgSource: require("../phone-images/galaxyNote9.png")
      },
      {
        id: "galaxyNote8",
        name: "Samsung Galaxy Note 8",
        technology: "GSM / HSPA / LTE",
        weight: "195g (6.88 oz)",
        displaySize: "6.3 inches",
        displayType: "Super AMOLED, 16M colors",
        displayResolution: "1440 x 2960 pixels",
        internalMemory: "64/128/256 GB, 6GB RAM",
        mainCamera: "Dual 12 MP, f/1.5-2.4",
        selfieCamera: "8 MP, f/1.7",
        sound: "Single speaker",
        OS: "Android 8.1 (Oreo)",
        battery: "Non-removable Li-ion 3300 mAh battery",
        imgSource: require("../phone-images/galaxyNote8.png")
      },
      {
        id: "galaxyS9Plus",
        name: "Samsung Galaxy S9+",
        technology: "GSM / CMDA / HSPA / EVDO / LTE",
        weight: "189g (6.67 oz)",
        displaySize: "6.2 inches",
        displayType: "Super AMOLED, 16M colors",
        displayResolution: "1440 x 2960 pixels",
        internalMemory: "64/128/256 GB, 6GB RAM",
        mainCamera: "Dual 12 MP, f/1.5-2.4",
        selfieCamera: "8 MP, f/1.7",
        sound: "Stereo speakers",
        OS: "Android 8.0 (Oreo)",
        battery: "Non-removable Li-ion 3500 mAh battery",
        imgSource: require("../phone-images/galaxyS9Plus.png")
      },
      {
        id: "galaxyS9",
        name: "Samsung Galaxy S9",
        technology: "GSM / CMDA / HSPA / EVDO / LTE",
        weight: "163g (5.75 oz)",
        displaySize: "5.8 inches",
        displayType: "Super AMOLED, 16M colors",
        displayResolution: "1440 x 2960 pixels",
        internalMemory: "64/128/256 GB, 4GB RAM",
        mainCamera: "12 MP, f/1.5-2.4",
        selfieCamera: "8 MP, f/1.7",
        sound: "Stereo speakers",
        OS: "Android 8.0 (Oreo)",
        battery: "Non-removable Li-ion 3000 mAh battery",
        imgSource: require("../phone-images/galaxyS9.png")
      },
      {
        id: "galaxyS8Plus",
        name: "Samsung Galaxy S8+",
        technology: "GSM / HSPA / LTE",
        weight: "173g (6.10 oz)",
        displaySize: "6.2 inches",
        displayType: "Super AMOLED, 16M colors",
        displayResolution: "1440 x 2960 pixels",
        internalMemory: "128 GB, 6GB RAM or 64 GB, 4 GB RAM",
        mainCamera: "12 MP, f/1.7",
        selfieCamera: "8 MP, f/1.7",
        sound: "Single speaker",
        OS: "Android 7.0 (Nougat)",
        battery: "Non-removable Li-ion 3500 mAh battery",
        imgSource: require("../phone-images/galaxyS8Plus.png")
      },
      {
        id: "galaxyS8",
        name: "Samsung Galaxy S8",
        technology: "GSM / HSPA / LTE",
        weight: "155g (5.47 oz)",
        displaySize: "5.8 inches",
        displayType: "Super AMOLED, 16M colors",
        displayResolution: "1440 x 2960 pixels",
        internalMemory: "64 GB, 4 GB RAM",
        mainCamera: "12 MP, f/1.7",
        selfieCamera: "8 MP, f/1.7",
        sound: "Single speaker",
        OS: "Android 7.0 (Nougat)",
        battery: "Non-removable Li-ion 3000 mAh battery",
        imgSource: require("../phone-images/galaxyS8.png")
      },
      {
        id: "galaxyS7",
        name: "Samsung Galaxy S7",
        technology: "GSM / HSPA / LTE",
        weight: "152g (5.36 oz)",
        displaySize: "5.1 inches",
        displayType: "Super AMOLED, 16M colors",
        displayResolution: "1440 x 2560 pixels",
        internalMemory: "32/64 GB, 4 GB RAM",
        mainCamera: "12 MP, f/1.7",
        selfieCamera: "5 MP, f/1.7",
        sound: "Single speaker",
        OS: "Android 6.0 (Marshmallow)",
        battery: "Non-removable Li-ion 3000 mAh battery",
        imgSource: require("../phone-images/galaxyS7.png")
      }
    ],
    iPhones: [
      {
        id: "iphoneXsMax",
        name: "iPhone XS Max",
        technology: "GSM / CDMA / HSPA / EVDO / LTE",
        weight: "208g (7.34 oz)",
        displaySize: "6.5 inches",
        displayType: "Super AMOLED, 16M colors",
        displayResolution: "1242 x 2688 pixels",
        internalMemory: "64/256/512 GB, 4 GB RAM",
        mainCamera: "Dual 12 MP, f/1.8-2.4",
        selfieCamera: "7 MP, f/2.2",
        sound: "Stereo speakers",
        OS: "iOS 12",
        battery: "Non-removable Li-ion 3174 mAh battery",
        imgSource: require("../phone-images/iphoneXsMax.png")
      },
      {
        id: "iphoneXs",
        name: "iPhone XS",
        technology: "GSM / CDMA / HSPA / EVDO / LTE",
        weight: "177g (6.24 oz)",
        displaySize: "5.8 inches",
        displayType: "Super AMOLED, 16M colors",
        displayResolution: "1125 x 2436 pixels",
        internalMemory: "64/256/512 GB, 4 GB RAM",
        mainCamera: "Dual 12 MP, f/1.8-2.4",
        selfieCamera: "7 MP, f/2.2",
        sound: "Stereo speakers",
        OS: "iOS 12",
        battery: "Non-removable Li-ion 2658 mAh battery",
        imgSource: require("../phone-images/iphoneXs.png")
      },
      {
        id: "iphoneXR",
        name: "iPhone XR",
        technology: "GSM / CDMA / HSPA / EVDO / LTE",
        weight: "194g (6.84 oz)",
        displaySize: "6.1 inches",
        displayType: "IPS LCD, 16M colors",
        displayResolution: "828 x 1792 pixels",
        internalMemory: "64/256/512 GB, 4 GB RAM",
        mainCamera: "12 MP, f/1.8",
        selfieCamera: "7 MP, f/2.2",
        sound: "Stereo speakers",
        OS: "iOS 12",
        battery: "Non-removable Li-ion 2942 mAh battery",
        imgSource: require("../phone-images/iphoneXR.png")
      },
      {
        id: "iphoneX",
        name: "iPhone X",
        technology: "GSM / HSPA / LTE",
        weight: "174g (6.14 oz)",
        displaySize: "5.8 inches",
        displayType: "Super AMOLED, 16M colors",
        displayResolution: "1125 x 2436 pixels",
        internalMemory: "64/256 GB, 3 GB RAM",
        mainCamera: "Dual 12 MP, f/1.8-2.4",
        selfieCamera: "7 MP, f/2.2",
        sound: "Stereo speakers",
        OS: "iOS 11.1.1",
        battery: "Non-removable Li-ion 2716 mAh battery",
        imgSource: require("../phone-images/iphoneX.png")
      },
      {
        id: "iphone8",
        name: "iPhone 8",
        technology: "GSM / HSPA / LTE",
        weight: "148 g (5.22 oz)",
        displaySize: "4.7 inches",
        displayType: "LED-backlit IPS LCD, 16M colors",
        displayResolution: "750 x 1334 pixels",
        internalMemory: "64/256 GB, 2 GB RAM",
        mainCamera: "12 MP, f/1.8",
        selfieCamera: "7 MP, f/2.2",
        sound: "Stereo speakers",
        OS: "iOS 11",
        battery: "Non-removable Li-ion 1821 mAh battery",
        imgSource: require("../phone-images/iphone8.png")
      },
      {
        id: "iphone8Plus",
        name: "iPhone 8 Plus",
        technology: "GSM / HSPA / LTE",
        weight: "202 g (7.13 oz)",
        displaySize: "5.5 inches",
        displayType: "LED-backlit IPS LCD, 16M colors",
        displayResolution: "1080 x 1920 pixels",
        internalMemory: "64/256 GB, 3 GB RAM",
        mainCamera: "Dual 12 MP, f/1.8-2/8",
        selfieCamera: "7 MP, f/2.2",
        sound: "Stereo speakers",
        OS: "iOS 11",
        battery: "Non-removable Li-ion 2691 mAh battery",
        imgSource: require("../phone-images/iphone8Plus.png")
      },
      {
        id: "iphone7",
        name: "iPhone 7",
        technology: "GSM / CDMA / HSPA / EVDO / LTE",
        weight: "138 g (4.87 oz)",
        displaySize: "4.7 inches",
        displayType: "LED-backlit IPS LCD, 16M colors",
        displayResolution: "750 x 1334 pixels",
        internalMemory: "32/128/256 GB, 2 GB RAM",
        mainCamera: "12 MP, f/1.8",
        selfieCamera: "7 MP, f/2.2",
        sound: "Stereo speakers",
        OS: "iOS 10.0.1",
        battery: "Non-removable Li-ion 1960 mAh battery",
        imgSource: require("../phone-images/iphone7.png")
      },
      {
        id: "iphone6s",
        name: "iPhone 6s",
        technology: "GSM / CDMA / HSPA / EVDO / LTE",
        weight: "143 g (5.04 oz)",
        displaySize: "4.7 inches",
        displayType: "LED-backlit IPS LCD, 16M colors",
        displayResolution: "750 x 1334 pixels",
        internalMemory: "32/128/256 GB, 2 GB RAM",
        mainCamera: "12 MP, f/2.2",
        selfieCamera: "5 MP, f/2.2",
        sound: "Single speaker",
        OS: "iOS 9",
        battery: "Non-removable Li-ion 1715 mAh battery",
        imgSource: require("../phone-images/iphone6s.png")
      }
    ],
    huaweis: [
      {
        id: "huaweiMate20Pro",
        name: "Huawei Mate 20 Pro",
        technology: "GSM / HSPA / LTE",
        weight: "189 g (6.67 oz)",
        displaySize: "6.39 inches",
        displayType: "AMOLED, 16M colors",
        displayResolution: "1440 x 3120 pixels",
        internalMemory: "256 GB, 8 GB RAM or 128 GB, 6 GB RAM",
        mainCamera: "Tripple Camera: 40 MP f/1.8, 20MP f/2.2 and 8 MP f/2.4",
        selfieCamera: "24 MP, f/2.0",
        sound: "Stereo speakers",
        OS: "Android 9.0 (Pie)",
        battery: "Non-removable Li-ion 4200 mAh battery",
        imgSource: require("../phone-images/huaweiMate20Pro.png")
      },
      {
        id: "huaweiMate20X",
        name: "Huawei Mate 20 X",
        technology: "GSM / HSPA / LTE",
        weight: "232 g (8.18 oz)",
        displaySize: "7.2 inches",
        displayType: "AMOLED, 16M colors",
        displayResolution: "1080 x 2244 pixels",
        internalMemory: "128 GB, 6 GB RAM",
        mainCamera: "Tripple Camera: 40 MP f/1.8, 20MP f/2.2 and 8 MP f/2.4",
        selfieCamera: "24 MP, f/2.0",
        sound: "Stereo speakers",
        OS: "Android 9.0 (Pie)",
        battery: "Non-removable Li-ion 50000 mAh battery",
        imgSource: require("../phone-images/huaweiMate20X.png")
      },
      {
        id: "huaweiMate20Lite",
        name: "Huawei Mate 20 Lite",
        technology: "GSM / HSPA / LTE",
        weight: "172 g (6.07 oz)",
        displaySize: "6.3 inches",
        displayType: "LTPS IPS LCD, 16M colors",
        displayResolution: "1440 x 3120 pixels",
        internalMemory: "64 GB, 4/6 GB RAM",
        mainCamera: "Dual Camera: 20 MP f/1.8 and 2 MP depth sensor",
        selfieCamera: "Dual Camera: 24 MP f/2.0 and 2 MP depth sensor",
        sound: "Single speaker",
        OS: "Android 8.1 (Oreo)",
        battery: "Non-removable Li-ion 3750 mAh battery",
        imgSource: require("../phone-images/huaweiMate20Lite.png")
      },
      {
        id: "huaweiP20Pro",
        name: "Huawei P20 Pro",
        technology: "GSM / HSPA / LTE",
        weight: "180 g (6.35 oz)",
        displaySize: "6.1 inches",
        displayType: "AMOLED, 16M colors",
        displayResolution: "1080 x 2240 pixels",
        internalMemory: "256 GB, 8 GB RAM or 128 GB, 6 GB RAM",
        mainCamera: "Tripple Camera: 40 MP f/1.8, 20MP f/1.6 and 8 MP f/2.4",
        selfieCamera: "24 MP, f/2.0",
        sound: "Stereo speakers",
        OS: "Android 8.1 (Oreo)",
        battery: "Non-removable Li-ion 4000 mAh battery",
        imgSource: require("../phone-images/huaweiP20Pro.png")
      },
      {
        id: "huaweiP20",
        name: "Huawei P20",
        technology: "GSM / HSPA / LTE",
        weight: "165 g (5.82 oz)",
        displaySize: "5.8 inches",
        displayType: "LTPS IPS LCD, 16M colors",
        displayResolution: "1080 x 2240 pixels",
        internalMemory: "128 GB, 4 GB RAM",
        mainCamera: "Dual Camera: 12 MP f/1.8, 20MP f/1.6",
        selfieCamera: "24 MP, f/2.0",
        sound: "Stereo speakers",
        OS: "Android 8.1 (Oreo)",
        battery: "Non-removable Li-ion 3400 mAh battery",
        imgSource: require("../phone-images/huaweiP20.png")
      },
      {
        id: "huaweiP20Lite",
        name: "Huawei P20 Lite",
        technology: "GSM / HSPA / LTE",
        weight: "145 g (5.11 oz)",
        displaySize: "5.84 inches",
        displayType: "LTPS IPS LCD, 16M colors",
        displayResolution: "1080 x 2280 pixels",
        internalMemory: "32/64 GB, 4 GB RAM",
        mainCamera: "Dual Camera: 16 MP f/2.2, 2MP depth sensor",
        selfieCamera: "24 MP, f/2.0",
        sound: "Single speaker",
        OS: "Android 8.0 (Oreo)",
        battery: "Non-removable Li-ion 3000 mAh battery",
        imgSource: require("../phone-images/huaweiP20Lite.png")
      }
    ],
    googles: [
      {
        id: "googlePixel3Xl",
        name: "Google Pixel 3XL",
        technology: "GSM / CDMA / HSPA / EVDO / LTE",
        weight: "184 g (6.49 oz)",
        displaySize: "6.3 inches",
        displayType: "P-OLED, 16M colors",
        displayResolution: "1440 x 2960 pixels",
        internalMemory: "64/128 GB, 4 GB RAM",
        mainCamera: "12.2 MP, f/1.8",
        selfieCamera: "Dual 8 MP, f/1.8-2.2",
        sound: "Stereo speakers",
        OS: "Android 9.0 (Pie)",
        battery: "Non-removable Li-ion 3430 mAh battery",
        imgSource: require("../phone-images/googlePixel3Xl.png")
      },
      {
        id: "googlePixel3",
        name: "Google Pixel 3",
        technology: "GSM / CDMA / HSPA / EVDO / LTE",
        weight: "148 g (5.22 oz)",
        displaySize: "5.5 inches",
        displayType: "P-OLED, 16M colors",
        displayResolution: "1080 x 2160 pixels",
        internalMemory: "64/128 GB, 4 GB RAM",
        mainCamera: "12.2 MP, f/1.8",
        selfieCamera: "Dual 8 MP, f/1.8-2.2",
        sound: "Stereo speakers",
        OS: "Android 9.0 (Pie)",
        battery: "Non-removable Li-ion 2915 mAh battery",
        imgSource: require("../phone-images/googlePixel3.png")
      }
    ],
    sonies: [
      {
        id: "sonyXZ3",
        name: "Sony XZ3",
        technology: "GSM / HSPA / LTE",
        weight: "193 g (6.81 oz)",
        displaySize: "6.0 inches",
        displayType: "P-OLED, 16M colors",
        displayResolution: "1440 x 2880 pixels",
        internalMemory: "64 GB, 4 GB RAM or 64 GB, 6 GB RAM",
        mainCamera: "19 MP, f/2.0",
        selfieCamera: "13 MP, f/1.9",
        sound: "Stereo speakers",
        OS: "Android 9.0 (Pie)",
        battery: "Non-removable Li-ion 3300 mAh battery",
        imgSource: require("../phone-images/sonyXZ3.png")
      },
      {
        id: "sonyXZ2",
        name: "Sony XZ2",
        technology: "GSM / HSPA / LTE",
        weight: "198 g (6.98 oz)",
        displaySize: "5.7 inches",
        displayType: "IPS LCD, 16M colors",
        displayResolution: "1080 x 2160 pixels",
        internalMemory: "64 GB, 4 GB RAM or 64 GB, 6 GB RAM",
        mainCamera: "19 MP, f/2.0",
        selfieCamera: "5 MP, f/2.2",
        sound: "Stereo speakers",
        OS: "Android 8.0 (Oreo)",
        battery: "Non-removable Li-ion 3180 mAh battery",
        imgSource: require("../phone-images/sonyXZ2.png")
      },
      {
        id: "sonyXA2Plus",
        name: "Sony XA2 Plus",
        technology: "GSM / HSPA / LTE",
        weight: "205 g (7.23 oz)",
        displaySize: "6.0 inches",
        displayType: "IPS LCD, 16M colors",
        displayResolution: "1080 x 2160 pixels",
        internalMemory: "32/64 GB, 4/6 GB RAM",
        mainCamera: "23 MP, f/2.0",
        selfieCamera: "8 MP, f/2.4",
        sound: "Single speaker",
        OS: "Android 8.0 (Oreo)",
        battery: "Non-removable Li-ion 3580 mAh battery",
        imgSource: require("../phone-images/sonyXA2Plus.png")
      },
      {
        id: "sonyXA2",
        name: "Sony XA2",
        technology: "GSM / HSPA / LTE",
        weight: "171 g (6.03 oz)",
        displaySize: "5.2 inches",
        displayType: "IPS LCD, 16M colors",
        displayResolution: "1080 x 1920 pixels",
        internalMemory: "32 GB, 3 GB RAM",
        mainCamera: "23 MP, f/2.0",
        selfieCamera: "8 MP, f/2.4",
        sound: "Single speaker",
        OS: "Android 8.0 (Oreo)",
        battery: "Non-removable Li-ion 3300 mAh battery",
        imgSource: require("../phone-images/sonyXA2.png")
      }
    ]
  };
  render() {
    return (
      <PhoneContext.Provider value={this.state}>
        {this.props.children}
      </PhoneContext.Provider>
    );
  }
}

export const PhoneConsumer = PhoneContext.Consumer;
